fix(package-integrity): fails when package managers redirect (#1135)
PyPI recently moved their metadata URL to a different location, and added a redirect from the old one.

This causes the integrity checker to fail:

```console
Error: GET https://pypi.org/pypi/cdk8s_plus_23/json - HTTP 301 (Moved Permanently)
```

Add redirect handling using the `follow-redirects` package.

-----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.